# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 3f038eef72eb51a24d9e9199b910b771af3587413f9b67d27119f600263b098029574505199effdca7dab4bcc8aa62cf36b2528331fa9736d80b4de73ab46f63

test:
  secret_key_base: 10ab4fd5c4299864b6ad7e820b3d8c5e83e6fa9b1031d6a334442a511b339a5483c6fcefb4b9fa74ce3ab8ded404dcfc3b901041c50532366bf2f029b0154d54

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
